config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'suggestions#suggestions'

  get 'kelioniu-paieska', to: 'main#finder'
  get 'kontaktai', to: 'main#contacts'
  get 'apie', to: 'main#about'

  resources :trips

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :trip
end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
  has_many :images, dependent: :destroy

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :description, length: { maximum: 1000 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  include Clearance::Controller
  before_action :test

  def test
    @author = 'Rytis Simanavičius'
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# MainController
class MainController < ApplicationController
  def finder
    @title = 'Kelionių paieška'
  end

  def contacts
    @title = 'Kontaktai'
  end

  def about
    @title = 'DUK'
  end
end

app/controllers/suggestions_controller.rb
# frozen_string_literal: true

# SuggestionsController
class SuggestionsController < ApplicationController
  # Before setting the prices set pvm
  before_action :getpvm

  $pvm = 0.00

  # Calculate and set the prices for
  # views/suggestions/suggestions.html.erb template
  def suggestions
    @popular_left_price = format('%.2f', (1200.00 - (1200.00 * $pvm)))
    @popular_right_price = format('%.2f', (950.00 - (950.00 * $pvm)))
  end

  # Return pvm
  def getpvm
    $pvm = 0.27
  end
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

# TripsController
class TripsController < ApplicationController
  def index
    @title = 'Kelionių tvarkyklė'

    @trips = Trip.where('title LIKE ?', "%#{params[:search]}%")
  end

  def show
    @title = 'Apie kelionę'
    @trip = Trip.find(params[:id])
  end

  def new
    @title = 'Nauja kelionė'
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(params[:trip].permit(:title, :description, :price, :country, :region, :city))
    @trip.save
    redirect_to trips_path
  end

  def edit
    @title = 'Redaguoti kelionę'
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update_attributes(params[:trip].permit(:title, :description, :price, :country, :region, :city))
    redirect_to trips_path
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/trips_helper.rb
# frozen_string_literal: true

# TripsHelper
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to image_tag("logo.png"), "/" %>

      <div id="nav">
          <nav>
              <%= link_to('Pagrindinis', '/') %>
              <%= link_to('Kelionių paieška', '/kelioniu-paieska') %>
              <%= link_to('Kontaktai', '/kontaktai') %>
              <%= link_to('Apie mus', '/apie') %> |

              <% if current_user.try(:email) == "admin@gmail.com" %>
                <%= link_to('Tvarkyklė', '/trips') %>
              <% end %>

              <% if signed_in? %>
                Sveiki, <%= current_user.email %>!
                <%= button_to 'Atsijungti', sign_out_path, method: :delete %>
              <% else %>
                <%= link_to 'Prisijungti', sign_in_path %>
              <% end %>

              <div id="flash">
                <% flash.each do |key, value| %>
                  <div class="flash <%= key %>"><%= value %></div>
                <% end %>
              </div>
          </nav>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p class="footer_text">© 2020 Rytis Simanavičius</p>
    </footer>
  </body>
</html>

app/views/main/about.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>

    <div class="about_questions">
        <h1>Klausimas</h1>
        <p>Atsakymas</p>
        <h1>Klausimas</h1>
        <p>Atsakymas</p>
        <h1>Klausimas</h1>
        <p>Atsakymas</p>
    </div>
</main>

app/views/main/contacts.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>

    <div id="contacts_table">
        <table>
            <tr>
                <td>
                    <a href="https://www.facebook.com/"><img width="150px" src="facebook.png" alt="facebook"></a>
                </td>
                <td>
                    <a href="https://www.twitter.com/"><img width="150px" src="twitter.png" alt="twitter"></a>
                </td>
                <td>
                    <a href="https://www.instagram.com/"><img width="150px" src="instagram.png" alt="instagram"></a>
                </td>
            </tr>
            <tr>
                <td>
                    <p><a style="text-decoration: none;color:#6b6868;" href="#">@Traveler</a></p>
                </td>
                <td>
                    <p><a style="text-decoration: none;color:#6b6868;" href="#">@Traveler</a></p>
                </td>
                <td>
                    <p><a style="text-decoration: none;color:#6b6868;" href="#">@Traveler</a></p>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <p style="margin-top: 40px;">traveler@gmail.com</p>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <p>+37066600888</p>
                </td>
            </tr>
        </table>

        <table style="border-spacing: 0 50px; margin-bottom: 50px">
            <tr>
                <td>
                    <img width="300" height="300" src="office_worker_1.jpg" alt="alex_jones">
                </td>
                <td style="text-align: left">
                    <p style="font-size: 150%;">Direktorius</p><br>
                    <p>Petras</p>
                    <p>+37068459505</p>
                    <p>petras.petraitis@gmail.com</p>
                </td>
                <td style="padding-left: 200px;">
                    <img width="300" height="300" src="office_worker_2.jpg" alt="alex_jones">
                </td>
                <td style="text-align: left">
                    <p style="font-size: 150%;">Buhalterė</p><br>
                    <p>Kristina</p>
                    <p>+37067536912</p>
                    <p>kristina@gmail.com</p>
                </td>
            </tr>
            <tr></tr>
            <tr>
                <td>
                    <img width="300" height="300" src="office_worker_3.jpg" alt="alex_jones">
                </td>
                <td style="text-align: left;">
                    <p style="font-size: 150%;">Vadybininkas</p><br>
                    <p>Tomas</p>
                    <p>+37066423578</p>
                    <p>tomas@gmail.com</p>
                </td>
                <td style="padding-left: 200px;">
                    <img width="300" height="300" src="office_worker_4.jpg" alt="alex_jones">
                </td>
                <td style="text-align: left;">
                    <p style="font-size: 150%;">Administratorius</p><br>
                    <p>Linas</p>
                    <p>+37063355881</p>
                    <p>linas@gmail.com</p>
                </td>
            </tr>
        </table>
    </div>
</main>

app/views/main/finder.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>

    <div id="finder_table">
        <img style="float: right;opacity: 90%" width="755" src="showcase.jpg" alt="showcase">

        <table>
            <tr>
                <td>
                    <p>Valstybė:
                </td>
                <td>
                    <input type="text" list="salys"/>
                    <datalist id="salys">
                        <option>Lietuva</option>
                        <option>Latvija</option>
                        <option>Estija</option>
                        <option>...</option>
                    </datalist>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Regionas:</p>
                </td>
                <td>
                    <input type="text" list="regionai"/>
                    <datalist id="regionai">
                        <option>Bretanė</option>
                        <option>...</option>
                    </datalist>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Miestas:</p>
                </td>
                <td>
                    <input type="text" list="miestai"/>
                    <datalist id="miestai">
                        <option>Madridas</option>
                        <option>Vilnius</option>
                        <option>...</option>
                    </datalist>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Keliautojų skaičius:</p>
                </td>
                <td>
                    <input type="number"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Kaina žmogui (nuo - iki):</p>
                </td>
                <td style="text-align: center;">
                    <input style="width: 100px" type="number"/> - 
                    <input style="width: 100px" type="number"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Pradžios data:</p>
                </td>
                <td>
                    <input type="date"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Pabaigos data:</p>
                </td>
                <td>
                    <input type="date"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Reikalingas gidas:</p>
                </td>
                <td>
                    <input type="checkbox"/>
                </td>
            </tr>
            <tr>
                <td>

                </td>
                <td>
                    <button class="submit" type="button">Ieškoti</button>
                </td>
            </tr>
        </table>
    </div>
</main>

app/views/suggestions/suggestions.html.erb
<div id="main">
    <main>
        <div class="title">
            <p>Populiariausios kelionės</p>
        </div>
        <hr>
        <article class="article">
            <div class="left">
                <a href="#"><img src="brittany-france.jpg" alt="brittany-france"></a>
                <p>Bretanė, Prancūzija<br><%= @popular_left_price %>€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="right">
                <a href="#"><img src="costa_del_sol-spain.jpg" alt="costa_del_sol-spain"></a>
                <p>Costa Del Sol, Ispanija<br><%= @popular_right_price %>€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </article>

        <div class="title">
            <p>Pigiausios kelionės</p>
        </div>
        <hr>
        <div class="article">
            <div class="left">
                <a href="#"><img src="koh_samui-thailand.jpg" alt="koh_samui-thailand"></a>
                <p style="margin: 0">Koh Samui, Tailandas</p>
                <p><span class="price">999.00€</span> 799.00€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="right">
                <a href="#"><img src="menorca-spain.jpg" alt="menorca-spain"></a>
                <p style="margin: 0">Menorka, Ispanija</p>
                <p><span class="price">899.00€</span> 459.00€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>

        <div class="title">
            <p>Sezoninės kelionės</p>
        </div>
        <hr>
        <div class="article">
            <div class="left">
                <a href="#"><img src="negombo-sri_lanka.jpg" alt="negombo-sri_lanka"></a>
                <p>Negombo, Šri Lanka<br>659.00€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="right">
                <a href="#"><img src="valletta-malta.jpg" alt="valletta-malta"></a>
                <p>Valeta, Malta<br>899.00€</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </main>
</div>

app/views/trips/edit.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>
    
    <%= form_for @trip do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <%= f.label :description %>
        <%= f.text_area :description %>
        <br>
        <%= f.label :price %>
        <%= f.number_field :price, step: 0.01 %>
        <br>
        <%= f.label :country %>
        <%= f.text_field :country %>
        <br>
        <%= f.label :region %>
        <%= f.text_field :region %>
        <br>
        <%= f.label :city %>
        <%= f.text_field :city %>
        <br>
        <%= f.submit "Užsaugoti" %>
    <% end %>
</main>

app/views/trips/index.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>

    <%= form_tag(trips_path, method: 'get') do %>
        Ieškoti pavadinimo: <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag("Search") %>
    <% end %>

    <table class="w3-table-all">
        <tr>
            <th>ID</th>
            <th>Pavadinimas</th>
            <th>Apibūdinimas</th>
            <th>Kaina</th>
            <th>Šalis</th>
            <th>Regionas</th>
            <th>Miestas</th>
        </tr>
        <% @trips.each do |trip| %>
            <tr>
                <th> <%= trip.id %> </th>
                <th> <%= link_to trip.title, trip %> </th>
                <th> <%= trip.description %> </th>
                <th> <%= trip.price %> </th>
                <th> <%= trip.country %> </th> 
                <th> <%= trip.region %> </th>
                <th> <%= trip.city %> </th>
                <th> <%= link_to "Redaguoti", edit_trip_path(trip) %> </th>
                <th> <%= link_to "Ištrinti", trip, :method => :delete %> </th>
            </tr>
        <% end %>
    </table>

    <p><%= link_to "Pridėti", new_trip_path %></p>
</main>

app/views/trips/new.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>
    
    <%= form_for @trip do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <%= f.label :description %>
        <%= f.text_area :description %>
        <br>
        <%= f.label :price %>
        <%= f.number_field :price, step: 0.01 %>
        <br>
        <%= f.label :country %>
        <%= f.text_field :country %>
        <br>
        <%= f.label :region %>
        <%= f.text_field :region %>
        <br>
        <%= f.label :city %>
        <%= f.text_field :city %>
        <br>
        <%= f.submit "Sukurti" %>
    <% end %>
</main>

app/views/trips/show.html.erb
<main id="main">
    <div class="title">
        <p><%= @title %></p>
    </div>

    <div class="separation_line">
        <hr>
    </div>
    
    <%= @trip.title %><br>
    <%= @trip.description %><br>
    <%= @trip.price %><br>
    <%= @trip.country %><br>
    <%= @trip.region %><br>
    <%= @trip.city %><br>

    <%= link_to "Grįžti", trips_path %>
</main>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>